# Generated by Django 5.0.4 on 2024-04-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=78.97, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='long',
            field=models.DecimalField(decimal_places=6, default=56.76, max_digits=9),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
