# Generated by Django 5.0.4 on 2024-04-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_lat_user_long_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(),
        ),
    ]
