# Generated by Django 5.0.4 on 2024-04-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.URLField(default='https://fund-rest-framework.s3.amazonaws.com/ev.energy_logo.png'),
        ),
    ]
