# Generated by Django 5.0.4 on 2024-04-15 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medical_profiles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
